name: Tag Version

on:
    push:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        name: Tag New Version
        if: "!contains(github.event.head_commit.message , '[release]')"

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GH_TOKEN }}

            - name: Set Node.js 20.8.1
              uses: actions/setup-node@v3
              with:
                  node-version: 20.8.1

            - name: Install JS deps
              run: npm install

            - name: Tag Version
              run: ./node_modules/semantic-release/bin/semantic-release.js --no-ci
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}